name: dependencies_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - jupyterlab
    - numpy
    - pandas
    - matplotlib
    - scipy
    - scikit-learn
    - requests
